---
- name: Setup PostreSQL
  hosts: masters
  roles:
    - { role: 'postgres-setup', become: yes, tags: postgres }

- name: Setup Jenkins
  hosts: masters
  roles:
    - { role: 'jenkins-setup', become: yes, tags: jenkins }
