---
- name: Setup PostreSQL
  hosts: masters
  roles:
    - { role: 'postgres-setup', become: yes, tags: postgres }

- name: Setup Jenkins Master
  hosts: masters
  roles:
    - { role: 'jenkins-master-setup', become: yes, tags: ['jenkins', 'jenkins-master'] }

- name: Setup Jenkins Slave
  hosts: masters
  roles:
    - { role: 'jenkins-slave-setup', become: yes, tags: ['jenkins', 'jenkins-slave'] }
