---
- name: create nfs directory for slave data
  file:
    path: /srv/nfs/kubedata/jenkins-slave
    state: directory
    mode: 0666

- name: create objects directory
  file:
    path: "{{ jenkins_yamls_root }}"
    state: directory
    mode: 0755    

- name: copy objects
  template:
    src: jenkins-slave.yaml.j2
    dest: "{{ jenkins_yamls_root }}/jenkins-slave.yaml"

- name: create slave
  shell: "kubectl apply -f {{ jenkins_yamls_root }}/jenkins-slave.yaml >> jenkins_slave_setup.txt"
  args:
    chdir: $HOME
    creates: jenkins_slave_setup.txt