- name: stop firewall
  service:
    name: firewalld
    enabled: no
    state: stopped

- name: disable Swap
  shell: swapoff -a

- name: comment out Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(.*swap*)'
    replace: '#\1'

- name: disable SELinux
  command: setenforce 0

- name: disable SELinux on reboot
  selinux:
    state: disabled

- name: load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present

- name: ensure net.bridge.bridge-nf-call-iptables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: add Kubernetes' YUM repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes

- name: add Docker's YUM repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: install required packages
  yum:
    name:
      - wget
      - telnet
      - net-tools
      - yum-utils
      - nfs-utils
      - device-mapper-persistent-data
      - lvm2
      - docker-ce-18.06.2.ce
      - "kubectl-{{ kubernetes_version }}"
      - "kubelet-{{ kubernetes_version }}"
      - "kubeadm-{{ kubernetes_version }}"                            
    state: present
    update_cache: yes

- name: create /etc/docker directory
  file:
    path: /etc/docker
    state: directory

- name: custom /etc/docker/daemon.json
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json

- name: enable ip forwarding
  template:
    src: k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf

- name: start docker
  service:
    name: docker
    enabled: yes
    state: started

- name: start kublet
  service:
    name: kubelet
    enabled: yes
    state: started
