---
- name: create nfs directory for jenkins data
  file:
    path: /srv/nfs/kubedata/jenkins-master
    state: directory
    mode: 0666

- name: create objects directory
  file:
    path: "{{ jenkins_yamls_root }}"
    state: directory
    mode: 0755    

- name: copy jenkins-ns.yaml
  copy:
    src: jenkins-ns.yaml
    dest: "{{ jenkins_yamls_root }}/jenkins-ns.yaml"

- name: create jenkins namespace
  shell: kubectl apply -f {{ jenkins_yamls_root }}/jenkins-ns.yaml >> jenkins_ns.txt
  args:
    chdir: $HOME
    creates: jenkins_ns.txt

- name: copy objects
  template:
    src: jenkins-master.yaml.j2
    dest: "{{ jenkins_yamls_root }}/jenkins-master.yaml"

- name: create master
  shell: "kubectl apply -f {{ jenkins_yamls_root }}/jenkins-master.yaml >> jenkins_master_setup.txt"
  args:
    chdir: $HOME
    creates: jenkins_master_setup.txt
 