---
- name: create nfs directory for jenkins master data
  file:
    path: /srv/nfs/kubedata/jenkins-master
    state: directory
    mode: 0666

- name: create nfs directory for jenkins agent data
  file:
    path: /srv/nfs/kubedata/jenkins-agent
    state: directory
    mode: 0666    

- name: create objects directory
  file:
    path: "{{ jenkins_yamls_root }}"
    state: directory
    mode: 0755    

- name: copy objects
  template:
    src: jenkins.yaml.j2
    dest: "{{ jenkins_yamls_root }}/jenkins.yaml"

- name: create master
  shell: "kubectl apply -f {{ jenkins_yamls_root }}/jenkins.yaml >> jenkins_setup.txt"
  args:
    chdir: $HOME
    creates: jenkins_setup.txt
 