---
- name: initialize the cluster
  shell: "kubeadm init --apiserver-advertise-address={{ hostvars['master'].ansible_host }} --pod-network-cidr={{ kubernetes_network }} >> cluster_initialized.txt"
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: "{{ ansible_env.USER }}"

- name: install Pod network
  shell: kubectl apply -f https://raw.githubusercontent.com/ajurasz/kubernetes-qa-cluster/master/roles/master-setup/files/calico.yaml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: create Kubernetes objects directory
  file:
    path: $HOME/kube-yamls
    state: directory
    mode: 0755    
